version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tcc_wawa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_tcc_schedule
      POSTGRES_PASSWORD: password_tcc_schedule
      POSTGRES_DB: tcc_schedule_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
